In [4]:
#يمكن عمل المضصفوفة المنطقية عن طريق عمل عامل منطقي علي مصفوفة عادية اخري 
import numpy as np

a = np.reshape(np.arange(16), (4,4)) # create a 4x4 array of integers
print(a)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [5]:
large_values = (a > 10) # test which elements of a are greated than 10
print(large_values)

[[False False False False]
 [False False False False]
 [False False False  True]
 [ True  True  True  True]]


In [6]:
even_values = (a%2 == 0) # test which elements of a are even
print(even_values)

[[ True False  True False]
 [ True False  True False]
 [ True False  True False]
 [ True False  True False]]
